config/routes.rb
Rails.application.routes.draw do
  resources :avaliacoes
  root to: "avaliacoes#index"
  post "/avaliar" => "avaliacoes#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avaliacao.rb
class Avaliacao < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/avaliacoes_controller.rb
class AvaliacoesController < ApplicationController
  before_action :set_avaliacao, only: [:show, :edit, :update, :destroy]

  # GET /avaliacoes
  # GET /avaliacoes.json
  def index
    @avaliacoes = Avaliacao.all
  end

  # GET /avaliacoes/1
  # GET /avaliacoes/1.json
  def show
  end

  # GET /avaliacoes/new
  def new
    @avaliacao = Avaliacao.new
  end

  # GET /avaliacoes/1/edit
  def edit
  end

  # POST /avaliacoes
  # POST /avaliacoes.json
  def create
    @avaliacao = Avaliacao.new(avaliacao_params)

    respond_to do |format|
      if @avaliacao.save
        format.html { redirect_to @avaliacao, notice: 'Avaliacao was successfully created.' }
        format.json { render :show, status: :created, location: @avaliacao }
      else
        format.html { render :new }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avaliacoes/1
  # PATCH/PUT /avaliacoes/1.json
  def update
    respond_to do |format|
      if @avaliacao.update(avaliacao_params)
        format.html { redirect_to @avaliacao, notice: 'Avaliacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @avaliacao }
      else
        format.html { render :edit }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avaliacoes/1
  # DELETE /avaliacoes/1.json
  def destroy
    @avaliacao.destroy
    respond_to do |format|
      format.html { redirect_to avaliacoes_url, notice: 'Avaliacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avaliacao
      @avaliacao = Avaliacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avaliacao_params
      params.require(:avaliacao).permit(:nome, :estrelas, :comentario)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avaliacoes_helper.rb
module AvaliacoesHelper
end

app/views/avaliacoes/_form.html.erb
<%= form_for(avaliacao, url: "/avaliar") do |f| %>
  <% if avaliacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(avaliacao.errors.count, "error") %> prohibited this avaliacao from being saved:</h2>

      <ul>
      <% avaliacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :estrelas %>
    <%= f.number_field :estrelas %>
  </div>

  <div class="field">
    <%= f.label :comentario %>
    <%= f.text_area :comentario %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avaliacoes/edit.html.erb
<h1>Editing Avaliacao</h1>

<%= render 'form', avaliacao: @avaliacao %>

<%= link_to 'Show', @avaliacao %> |
<%= link_to 'Back', avaliacoes_path %>

app/views/avaliacoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Avaliacoes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Estrelas</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avaliacoes.each do |avaliacao| %>
      <tr>
        <td><%= avaliacao.nome %></td>
        <td><%= avaliacao.estrelas %></td>
        <td><%= avaliacao.comentario %></td>
        <td><%= link_to 'Show', avaliacao %></td>
        <td><%= link_to 'Edit', edit_avaliacao_path(avaliacao) %></td>
        <td><%= link_to 'Destroy', avaliacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avaliacao', new_avaliacao_path %>

app/views/avaliacoes/new.html.erb
<h1>New Avaliacao</h1>

<%= render 'form', avaliacao: @avaliacao %>

<%= link_to 'Back', avaliacoes_path %>

app/views/avaliacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @avaliacao.nome %>
</p>

<p>
  <strong>Estrelas:</strong>
  <%= @avaliacao.estrelas %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @avaliacao.comentario %>
</p>

<%= link_to 'Edit', edit_avaliacao_path(@avaliacao) %> |
<%= link_to 'Back', avaliacoes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AvaliacaoInfoway</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>